# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'x.x'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create zip
        run: |            
          zip -r DenonAvpControl_${{ github.event.inputs.release_version }}.zip DenonAvpControl
          echo "ZIP_SHA=$(sha1sum DenonAvpControl_${{ github.event.inputs.release_version }}.zip | cut -d " " -f1)" >> $GITHUB_ENV

      - name: Create Release
        # You may pin to the exact commit or the version.
        # uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: # optional, default is 
            DenonAvpControl_${{ github.event.inputs.release_version }}.zip
          tag:
            ${{ github.event.inputs.release_version }}
      
      - name: xml-replace-action
        # You may pin to the exact commit or the version.
        # uses: rvolo/xml-replace-action@7e4c7097f298b34cb371ff3b0f2f6413593a6faa
        uses: rvolo/xml-replace-action@v0.3
        with:
          # path in filesystem to xml file
          filepath: 
            repo.xml
          # Xpath to use when getting nodes
          xpath:
            /extensions/plugins/plugin/@version
          # value to replace with
          replace:
            ${{ github.event.inputs.release_version }}

      - name: xml-replace-action
        # You may pin to the exact commit or the version.
        # uses: rvolo/xml-replace-action@7e4c7097f298b34cb371ff3b0f2f6413593a6faa
        uses: rvolo/xml-replace-action@v0.3
        with:
          # path in filesystem to xml file
          filepath: 
            repo.xml
          # Xpath to use when getting nodes
          xpath:
            /extensions/plugins/plugin/sha
          # value to replace with
          replace:
            ${{ env.ZIP_SHA }}
      
      - name: xml-replace-action
        # You may pin to the exact commit or the version.
        # uses: rvolo/xml-replace-action@7e4c7097f298b34cb371ff3b0f2f6413593a6faa
        uses: rvolo/xml-replace-action@v0.3
        with:
          # path in filesystem to xml file
          filepath: 
            repo.xml
          # Xpath to use when getting nodes
          xpath:
            /extensions/plugins/plugin/url
          # value to replace with
          replace:
            https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.release_version }}/DenonAvpControl_${{ github.event.inputs.release_version }}.zip

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update repo.xml with latest release  
          file_pattern: 'repo.xml'

