# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set Version
        id: set-version
        run:
          echo "version=`egrep -o "version>(.*)</version" DenonAvpControl/install.xml | egrep -o \"[0-9.]*\"`" >> $GITHUB_OUTPUT

      - name: Create zip
        run: |            
          zip -r DenonAvpControl.zip DenonAvpControl
      
      - name: Setup Perl
        run: |
          sudo apt-get install -y libxml-simple-perl libdigest-sha-perl

      - name: Update SHA and Version in repo.xml
        id: tag
        run: |
          url="https://github.com/${{ github.repository }}/releases/download/${{ steps.set-version.outputs.version }}"
          perl release.pl repo.xml ${{ steps.set-version.outputs.version }} DenonAvpControl.zip $url

      - name: Update Repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add repo.xml
          git commit -m "Update repo.xml for release ${{ steps.set-version.outputs.version }}"
          git push origin HEAD:master
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-version.outputs.version }}
          name: Version ${{ steps.set-version.outputs.version }}
          body: DenonAvpControl Plugin Release
          draft: false
          prerelease: false
          files: DenonAvpControl.zip
